#!/bin/bash

# github repo
REPO=linebender/resvg

SRC=$(realpath $(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd))

set -e

WORKDIR=$HOME/src/charts

BUILD_TARGETS=""
MODULES_ONLY=0

OPTIND=1
while getopts "t:m" opt; do
case "$opt" in
  t) BUILD_TARGETS="$OPTARG" ;;
  m) MODULES_ONLY=1 ;;
esac
done

mkdir -p $WORKDIR

git_latest_tag() {
  git -C "$1" describe --abbrev=0 --tags
}

git_checkout_reset() {
  local dir="$WORKDIR/$1" name="$1" repo="$2"
  if [ ! -d "$dir" ]; then
    (set -x;
      git clone "$repo" "$dir"
    )
  fi
  (set -x;
    git -C "$dir" fetch origin
  )
  local ver=$(git_latest_tag "$dir")
  echo "$name $ver"
  echo "$ver" > "$SRC/version.txt"
  (set -x;
    git -C "$dir" reset --hard
    git -C "$dir" clean -f -x -d -e node_modules
    git -C "$dir" checkout "$ver" &> /dev/null
  )
}

declare -A TARGETS=(
  [darwin_amd64]=x86_64-apple-darwin
  [darwin_arm64]=aarch64-apple-darwin
  [linux_amd64]=x86_64-unknown-linux-gnu
  [linux_arm64]=aarch64-unknown-linux-gnu
  [linux_arm]=armv7-unknown-linux-gnueabihf
  [windows_amd64]=x86_64-pc-windows-gnu
)

#[dragonfly_amd64]=
#[freebsd_amd64]=x86_64-unknown-freebsd
#[netbsd_amd64]=x86_64-unknown-netbsd
#[openbsd_amd64]=
#[solaris_amd64]=x86_64-pc-solaris
#[windows_arm64]=aarch64-pc-windows-msvc

# //go:build constraint for each target, used in the generated lib.go and
# link_*.go files.
declare -A GO_BUILD_TAG=(
  [darwin_amd64]="darwin && amd64"
  [darwin_arm64]="darwin && arm64"
  [linux_amd64]="linux && amd64"
  [linux_arm64]="linux && arm64"
  [linux_arm]="linux && arm"
  [windows_amd64]="windows && amd64"
)

# System libraries each target needs on top of libresvg.a itself, emitted
# into the generated lib.go.
declare -A SYSTEM_LIBS=(
  [darwin_amd64]="-lresvg -lm"
  [darwin_arm64]="-lresvg -lm"
  [linux_amd64]="-lresvg -lm"
  [linux_arm64]="-lresvg -lm"
  [linux_arm]="-lresvg -lm"
  [windows_amd64]="-lresvg -lm -lkernel32 -ladvapi32 -lbcrypt -lntdll -luserenv -lws2_32"
)

# Each target ships as its own Go module nested under libresvg/, so a
# consumer downloads only the archive for the platform it is building for.
# The go command fetches a module's zip only when a package it provides is
# actually in the build, and the imports live in build-tagged link_*.go files
# at the repository root. See libresvg/README.md.
MODULE_GO_DIRECTIVE="1.21"

# write_module TARGET writes libresvg/TARGET/{go.mod,doc.go,lib.go} and the
# root link_TARGET.go, from the archive already at libresvg/TARGET/libresvg.a.
write_module() {
  local target="$1" dir="$SRC/libresvg/$1" tag="${GO_BUILD_TAG[$1]}" libs="${SYSTEM_LIBS[$1]}"

  cat > "$dir/go.mod" << __END__
module github.com/xo/resvg/libresvg/$target

go $MODULE_GO_DIRECTIVE
__END__

  cat > "$dir/doc.go" << __END__
// Package lib ships the prebuilt resvg static archive for $target and the
// cgo link flags that go with it. It has no API: import it for its side
// effect on the link, which is what github.com/xo/resvg does.
//
// Code generated by gen.sh. DO NOT EDIT.
package lib
__END__

  cat > "$dir/lib.go" << __END__
// Code generated by gen.sh. DO NOT EDIT.

//go:build $tag

package lib

/*
#cgo LDFLAGS: -L\${SRCDIR} $libs
*/
import "C"
__END__

  cat > "$SRC/link_$target.go" << __END__
// Code generated by gen.sh. DO NOT EDIT.

//go:build $tag

package resvg

// Blank import for the link only: the package has no API, it just carries
// the $target archive and the #cgo LDFLAGS naming it. Because this file is
// build-tagged, the go command never downloads the other five platforms'
// modules when building for this one.
import _ "github.com/xo/resvg/libresvg/$target"
__END__
}

if [ -z "$BUILD_TARGETS" ]; then
  BUILD_TARGETS="${!TARGETS[@]}"
fi

BUILD_TARGETS=$(sed -e 's/\s\+/\n/g' <<< "$BUILD_TARGETS" | sort -i |tr '\n' ' ')

if [ "$MODULES_ONLY" -eq 1 ]; then
  for TARGET in $BUILD_TARGETS; do
    write_module "$TARGET"
  done
  exit 0
fi

git_checkout_reset resvg "https://github.com/${REPO}.git"

for f in $(find $WORKDIR/resvg -type f -name Cargo.toml); do
  cat > $(dirname "$f")/Cross.toml << __END__
[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross:local"

[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"
__END__
done

mkdir -p $SRC/libresvg
(set -x;
  cp $WORKDIR/resvg/crates/c-api/resvg.h $SRC/libresvg
)

pushd $WORKDIR/resvg/crates/c-api &> /dev/null
for TARGET in $BUILD_TARGETS; do
  echo -e "\n\nBUILDING $TARGET"
  DEST=$SRC/libresvg/$TARGET
  mkdir -p $DEST
  RUST_TARGET="${TARGETS[$TARGET]}"
  if [ -z "$(rustup target list|grep "$RUST_TARGET"|grep installed)" ]; then
    (set -x;
      rustup target add $RUST_TARGET
    )
  fi
  (
    export "CARGO_TARGET_$(sed -e 's/-/_/g' <<< "$RUST_TARGET"|tr [:lower:] [:upper:])_RUSTFLAGS"="--print=native-static-libs"
    set -x
    cross build \
      --verbose \
      --release \
      --target $RUST_TARGET
    cp $WORKDIR/resvg/target/$RUST_TARGET/release/libresvg.a $DEST/libresvg.a
    chmod -x $DEST/libresvg.a
  )
  write_module "$TARGET"
done
popd &> /dev/null

# Operational standard: a libresvg/<target> module is tagged with the same
# version as the vendored resvg release it carries (version.txt), never an
# independent version of its own. Bump the require block in go.mod to match
# before tagging the root module.
VER=$(cat "$SRC/version.txt")
echo -e "\n\nUpdate the require block in go.mod to $VER, then run:"
TAGS=()
for TARGET in $BUILD_TARGETS; do
  TAGS+=("libresvg/$TARGET/$VER")
  echo "  git tag libresvg/$TARGET/$VER"
done
echo "  git push origin ${TAGS[@]}"
echo "then tag and push the root module."
