// Code generated by gen.sh. DO NOT EDIT.

//go:build darwin && arm64

package resvg

// Blank import for the link only: the package has no API, it just carries
// the darwin_arm64 archive and the #cgo LDFLAGS naming it. Because this file is
// build-tagged, the go command never downloads the other five platforms'
// modules when building for this one.
import _ "github.com/xo/resvg/libresvg/darwin_arm64"
