// Code generated by gen.sh. DO NOT EDIT.

//go:build windows && amd64

package resvg

// Blank import for the link only: the package has no API, it just carries
// the windows_amd64 archive and the #cgo LDFLAGS naming it. Because this file is
// build-tagged, the go command never downloads any other platform's module
// when building for this one.
import _ "github.com/xo/resvg/libresvg/windows_amd64"
