// Code generated by gen.sh. DO NOT EDIT.

//go:build linux && amd64 && musl

package resvg

// Blank import for the link only: the package has no API, it just carries
// the linux_amd64_musl archive and the #cgo LDFLAGS naming it. Because this file is
// build-tagged, the go command never downloads any other platform's module
// when building for this one.
import _ "github.com/xo/resvg/libresvg/linux_amd64_musl"
