// Package lib ships the prebuilt resvg static archive for windows_amd64 and the
// cgo link flags that go with it. It has no API: import it for its side
// effect on the link, which is what github.com/xo/resvg does.
//
// Code generated by gen.sh. DO NOT EDIT.
package lib
